### ISSUE TITLE
How do we know who has rented what?

### ISSUE THREAD

**Issue by bipol** [airn/Rentr#3]
There is no tracking of customer phone numbers and other bullshit.

**Comment by airn** [comment]
So we should create a new model called "Rental" that stores custName, custPhoneNum, custEmail, rentableId, price and then remove the price field from the Rentable model.

**Comment by bipolalam** [comment]
I like it! So I'm going to add a milestone for shits and giggles

**Comment by bipol** [comment]
Why is price on the rental side, and not the object side?

**Comment by airn** [comment]
It allows the renter to change it up and keep a record of how much was made for the day.
