### ISSUE TITLE
Create Rental 

### ISSUE THREAD

**Issue by bipol** [airn/Rentr#7]
From issue #3 
So we should create a new model called "Rental" that stores custName, custPhoneNum, custEmail, rentableId, price and then remove the price field from the Rentable model.

**Comment by shiguna** [comment]
Added. Used rentableID as a fk to Rentable.

**Comment by bipol** [comment]
@shiguna: Couple quick things -

when commiting fixes to issues, say something like "Fixed #(issue number) - blah blah" - this will link the commit to this issue.

also, we don't need the ID part of that variable - while the variable does contain a number, whenever it is called within Django it returns the actual object!  So it is more aptly named simply as rentable.
